// This file is auto-generated by @hey-api/openapi-ts

import type { Client, Options as Options2, TDataShape } from './client';
import { client } from './client.gen';
import type { AppControllerGetHelloData, AppControllerGetHelloResponses, AuthControllerForgotPasswordData, AuthControllerForgotPasswordResponses, AuthControllerLoginData, AuthControllerLoginErrors, AuthControllerLoginResponses, AuthControllerLogoutData, AuthControllerLogoutResponses, AuthControllerRefreshData, AuthControllerRefreshResponses, AuthControllerRegisterData, AuthControllerRegisterErrors, AuthControllerRegisterResponses, AuthControllerResetPasswordData, AuthControllerResetPasswordErrors, AuthControllerResetPasswordResponses, AuthControllerVerifyEmailData, AuthControllerVerifyEmailErrors, AuthControllerVerifyEmailResponses, LessonControllerCreateData, LessonControllerCreateResponses, LessonControllerFindAllData, LessonControllerFindAllResponses, LessonControllerFindOneData, LessonControllerFindOneResponses, LessonControllerRemoveData, LessonControllerRemoveResponses, LessonControllerUpdateData, LessonControllerUpdateResponses, UserControllerCreateData, UserControllerCreateResponses, UserControllerFindAllData, UserControllerFindAllResponses, UserControllerFindOneData, UserControllerFindOneResponses, UserControllerRemoveData, UserControllerRemoveResponses, UserControllerUpdateData, UserControllerUpdateResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> = Options2<TData, ThrowOnError> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

/**
 * Get hello message
 */
export const appControllerGetHello = <ThrowOnError extends boolean = false>(options?: Options<AppControllerGetHelloData, ThrowOnError>) => (options?.client ?? client).get<AppControllerGetHelloResponses, unknown, ThrowOnError>({ url: '/api/v1', ...options });

/**
 * Register a new user
 */
export const authControllerRegister = <ThrowOnError extends boolean = false>(options: Options<AuthControllerRegisterData, ThrowOnError>) => (options.client ?? client).post<AuthControllerRegisterResponses, AuthControllerRegisterErrors, ThrowOnError>({
    url: '/api/v1/auth/register',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Login user
 */
export const authControllerLogin = <ThrowOnError extends boolean = false>(options: Options<AuthControllerLoginData, ThrowOnError>) => (options.client ?? client).post<AuthControllerLoginResponses, AuthControllerLoginErrors, ThrowOnError>({
    url: '/api/v1/auth/login',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Verify user email
 */
export const authControllerVerifyEmail = <ThrowOnError extends boolean = false>(options: Options<AuthControllerVerifyEmailData, ThrowOnError>) => (options.client ?? client).post<AuthControllerVerifyEmailResponses, AuthControllerVerifyEmailErrors, ThrowOnError>({
    url: '/api/v1/auth/verify-email',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Request password reset
 */
export const authControllerForgotPassword = <ThrowOnError extends boolean = false>(options: Options<AuthControllerForgotPasswordData, ThrowOnError>) => (options.client ?? client).post<AuthControllerForgotPasswordResponses, unknown, ThrowOnError>({
    url: '/api/v1/auth/forgot-password',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Reset user password
 */
export const authControllerResetPassword = <ThrowOnError extends boolean = false>(options: Options<AuthControllerResetPasswordData, ThrowOnError>) => (options.client ?? client).post<AuthControllerResetPasswordResponses, AuthControllerResetPasswordErrors, ThrowOnError>({
    url: '/api/v1/auth/reset-password',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

export const authControllerRefresh = <ThrowOnError extends boolean = false>(options?: Options<AuthControllerRefreshData, ThrowOnError>) => (options?.client ?? client).post<AuthControllerRefreshResponses, unknown, ThrowOnError>({ url: '/api/v1/auth/refresh', ...options });

export const authControllerLogout = <ThrowOnError extends boolean = false>(options?: Options<AuthControllerLogoutData, ThrowOnError>) => (options?.client ?? client).post<AuthControllerLogoutResponses, unknown, ThrowOnError>({ url: '/api/v1/auth/logout', ...options });

export const userControllerFindAll = <ThrowOnError extends boolean = false>(options?: Options<UserControllerFindAllData, ThrowOnError>) => (options?.client ?? client).get<UserControllerFindAllResponses, unknown, ThrowOnError>({ url: '/api/v1/user', ...options });

export const userControllerCreate = <ThrowOnError extends boolean = false>(options: Options<UserControllerCreateData, ThrowOnError>) => (options.client ?? client).post<UserControllerCreateResponses, unknown, ThrowOnError>({
    url: '/api/v1/user',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

export const userControllerRemove = <ThrowOnError extends boolean = false>(options: Options<UserControllerRemoveData, ThrowOnError>) => (options.client ?? client).delete<UserControllerRemoveResponses, unknown, ThrowOnError>({ url: '/api/v1/user/{id}', ...options });

export const userControllerFindOne = <ThrowOnError extends boolean = false>(options: Options<UserControllerFindOneData, ThrowOnError>) => (options.client ?? client).get<UserControllerFindOneResponses, unknown, ThrowOnError>({ url: '/api/v1/user/{id}', ...options });

export const userControllerUpdate = <ThrowOnError extends boolean = false>(options: Options<UserControllerUpdateData, ThrowOnError>) => (options.client ?? client).patch<UserControllerUpdateResponses, unknown, ThrowOnError>({
    url: '/api/v1/user/{id}',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

export const lessonControllerFindAll = <ThrowOnError extends boolean = false>(options?: Options<LessonControllerFindAllData, ThrowOnError>) => (options?.client ?? client).get<LessonControllerFindAllResponses, unknown, ThrowOnError>({ url: '/api/v1/lesson', ...options });

export const lessonControllerCreate = <ThrowOnError extends boolean = false>(options: Options<LessonControllerCreateData, ThrowOnError>) => (options.client ?? client).post<LessonControllerCreateResponses, unknown, ThrowOnError>({
    url: '/api/v1/lesson',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

export const lessonControllerRemove = <ThrowOnError extends boolean = false>(options: Options<LessonControllerRemoveData, ThrowOnError>) => (options.client ?? client).delete<LessonControllerRemoveResponses, unknown, ThrowOnError>({ url: '/api/v1/lesson/{id}', ...options });

export const lessonControllerFindOne = <ThrowOnError extends boolean = false>(options: Options<LessonControllerFindOneData, ThrowOnError>) => (options.client ?? client).get<LessonControllerFindOneResponses, unknown, ThrowOnError>({ url: '/api/v1/lesson/{id}', ...options });

export const lessonControllerUpdate = <ThrowOnError extends boolean = false>(options: Options<LessonControllerUpdateData, ThrowOnError>) => (options.client ?? client).patch<LessonControllerUpdateResponses, unknown, ThrowOnError>({
    url: '/api/v1/lesson/{id}',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});
