// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: string;
};

export type RegisterDto = {
    /**
     * User email address
     */
    email: string;
    /**
     * Password with uppercase, lowercase, number and special character
     */
    password: string;
    /**
     * User first name
     */
    firstName: string;
    /**
     * User last name
     */
    lastName: string;
    /**
     * User native language
     */
    nativeLanguage: string;
    /**
     * Language user wants to learn
     */
    learningLanguage: string;
};

export type LoginDto = {
    /**
     * User email address
     */
    email: string;
    /**
     * User password
     */
    password: string;
};

export type VerifyEmailDto = {
    /**
     * Email verification token
     */
    token: string;
};

export type ForgotPasswordDto = {
    /**
     * Email address to send reset link
     */
    email: string;
};

export type ResetPasswordDto = {
    /**
     * Password reset token
     */
    token: string;
    /**
     * New password with uppercase, lowercase, number and special character
     */
    newPassword: string;
};

export type CreateUserDto = {
    [key: string]: unknown;
};

export type UpdateUserDto = {
    [key: string]: unknown;
};

export type CreateLessonDto = {
    [key: string]: unknown;
};

export type UpdateLessonDto = {
    [key: string]: unknown;
};

export type AppControllerGetHelloData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1';
};

export type AppControllerGetHelloResponses = {
    /**
     * Returns hello message
     */
    200: unknown;
};

export type AuthControllerRegisterData = {
    body: RegisterDto;
    path?: never;
    query?: never;
    url: '/api/v1/auth/register';
};

export type AuthControllerRegisterErrors = {
    /**
     * Email already exists
     */
    409: unknown;
};

export type AuthControllerRegisterResponses = {
    /**
     * User registered successfully
     */
    201: unknown;
};

export type AuthControllerLoginData = {
    body: LoginDto;
    path?: never;
    query?: never;
    url: '/api/v1/auth/login';
};

export type AuthControllerLoginErrors = {
    /**
     * Invalid credentials
     */
    401: unknown;
};

export type AuthControllerLoginResponses = {
    /**
     * Login successful
     */
    200: unknown;
};

export type AuthControllerVerifyEmailData = {
    body: VerifyEmailDto;
    path?: never;
    query?: never;
    url: '/api/v1/auth/verify-email';
};

export type AuthControllerVerifyEmailErrors = {
    /**
     * Invalid token
     */
    400: unknown;
};

export type AuthControllerVerifyEmailResponses = {
    /**
     * Email verified successfully
     */
    200: unknown;
};

export type AuthControllerForgotPasswordData = {
    body: ForgotPasswordDto;
    path?: never;
    query?: never;
    url: '/api/v1/auth/forgot-password';
};

export type AuthControllerForgotPasswordResponses = {
    /**
     * Reset link sent if account exists
     */
    200: unknown;
};

export type AuthControllerResetPasswordData = {
    body: ResetPasswordDto;
    path?: never;
    query?: never;
    url: '/api/v1/auth/reset-password';
};

export type AuthControllerResetPasswordErrors = {
    /**
     * Invalid or expired token
     */
    400: unknown;
};

export type AuthControllerResetPasswordResponses = {
    /**
     * Password reset successfully
     */
    200: unknown;
};

export type AuthControllerRefreshData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/auth/refresh';
};

export type AuthControllerRefreshResponses = {
    201: unknown;
};

export type AuthControllerLogoutData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/auth/logout';
};

export type AuthControllerLogoutResponses = {
    201: unknown;
};

export type UserControllerFindAllData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/user';
};

export type UserControllerFindAllResponses = {
    200: unknown;
};

export type UserControllerCreateData = {
    body: CreateUserDto;
    path?: never;
    query?: never;
    url: '/api/v1/user';
};

export type UserControllerCreateResponses = {
    201: unknown;
};

export type UserControllerRemoveData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/v1/user/{id}';
};

export type UserControllerRemoveResponses = {
    200: unknown;
};

export type UserControllerFindOneData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/v1/user/{id}';
};

export type UserControllerFindOneResponses = {
    200: unknown;
};

export type UserControllerUpdateData = {
    body: UpdateUserDto;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/v1/user/{id}';
};

export type UserControllerUpdateResponses = {
    200: unknown;
};

export type LessonControllerFindAllData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/lesson';
};

export type LessonControllerFindAllResponses = {
    200: unknown;
};

export type LessonControllerCreateData = {
    body: CreateLessonDto;
    path?: never;
    query?: never;
    url: '/api/v1/lesson';
};

export type LessonControllerCreateResponses = {
    201: unknown;
};

export type LessonControllerRemoveData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/v1/lesson/{id}';
};

export type LessonControllerRemoveResponses = {
    200: unknown;
};

export type LessonControllerFindOneData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/v1/lesson/{id}';
};

export type LessonControllerFindOneResponses = {
    200: unknown;
};

export type LessonControllerUpdateData = {
    body: UpdateLessonDto;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/v1/lesson/{id}';
};

export type LessonControllerUpdateResponses = {
    200: unknown;
};
