// This file is auto-generated by @hey-api/openapi-ts

import { type DefaultError, queryOptions, type UseMutationOptions } from '@tanstack/react-query';

import { client } from '../client.gen';
import { appControllerGetHello, authControllerForgotPassword, authControllerLogin, authControllerLogout, authControllerRefresh, authControllerRegister, authControllerResetPassword, authControllerVerifyEmail, lessonControllerCreate, lessonControllerFindAll, lessonControllerFindOne, lessonControllerRemove, lessonControllerUpdate, type Options, userControllerCreate, userControllerFindAll, userControllerFindOne, userControllerRemove, userControllerUpdate } from '../sdk.gen';
import type { AppControllerGetHelloData, AuthControllerForgotPasswordData, AuthControllerLoginData, AuthControllerLogoutData, AuthControllerRefreshData, AuthControllerRegisterData, AuthControllerResetPasswordData, AuthControllerVerifyEmailData, LessonControllerCreateData, LessonControllerFindAllData, LessonControllerFindOneData, LessonControllerRemoveData, LessonControllerUpdateData, UserControllerCreateData, UserControllerFindAllData, UserControllerFindOneData, UserControllerRemoveData, UserControllerUpdateData } from '../types.gen';

export type QueryKey<TOptions extends Options> = [
    Pick<TOptions, 'baseUrl' | 'body' | 'headers' | 'path' | 'query'> & {
        _id: string;
        _infinite?: boolean;
        tags?: ReadonlyArray<string>;
    }
];

const createQueryKey = <TOptions extends Options>(id: string, options?: TOptions, infinite?: boolean, tags?: ReadonlyArray<string>): [
    QueryKey<TOptions>[0]
] => {
    const params: QueryKey<TOptions>[0] = { _id: id, baseUrl: options?.baseUrl || (options?.client ?? client).getConfig().baseUrl } as QueryKey<TOptions>[0];
    if (infinite) {
        params._infinite = infinite;
    }
    if (tags) {
        params.tags = tags;
    }
    if (options?.body) {
        params.body = options.body;
    }
    if (options?.headers) {
        params.headers = options.headers;
    }
    if (options?.path) {
        params.path = options.path;
    }
    if (options?.query) {
        params.query = options.query;
    }
    return [params];
};

export const appControllerGetHelloQueryKey = (options?: Options<AppControllerGetHelloData>) => createQueryKey('appControllerGetHello', options);

/**
 * Get hello message
 */
export const appControllerGetHelloOptions = (options?: Options<AppControllerGetHelloData>) => queryOptions<unknown, DefaultError, unknown, ReturnType<typeof appControllerGetHelloQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await appControllerGetHello({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: appControllerGetHelloQueryKey(options)
});

/**
 * Register a new user
 */
export const authControllerRegisterMutation = (options?: Partial<Options<AuthControllerRegisterData>>): UseMutationOptions<unknown, DefaultError, Options<AuthControllerRegisterData>> => {
    const mutationOptions: UseMutationOptions<unknown, DefaultError, Options<AuthControllerRegisterData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await authControllerRegister({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

/**
 * Login user
 */
export const authControllerLoginMutation = (options?: Partial<Options<AuthControllerLoginData>>): UseMutationOptions<unknown, DefaultError, Options<AuthControllerLoginData>> => {
    const mutationOptions: UseMutationOptions<unknown, DefaultError, Options<AuthControllerLoginData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await authControllerLogin({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

/**
 * Verify user email
 */
export const authControllerVerifyEmailMutation = (options?: Partial<Options<AuthControllerVerifyEmailData>>): UseMutationOptions<unknown, DefaultError, Options<AuthControllerVerifyEmailData>> => {
    const mutationOptions: UseMutationOptions<unknown, DefaultError, Options<AuthControllerVerifyEmailData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await authControllerVerifyEmail({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

/**
 * Request password reset
 */
export const authControllerForgotPasswordMutation = (options?: Partial<Options<AuthControllerForgotPasswordData>>): UseMutationOptions<unknown, DefaultError, Options<AuthControllerForgotPasswordData>> => {
    const mutationOptions: UseMutationOptions<unknown, DefaultError, Options<AuthControllerForgotPasswordData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await authControllerForgotPassword({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

/**
 * Reset user password
 */
export const authControllerResetPasswordMutation = (options?: Partial<Options<AuthControllerResetPasswordData>>): UseMutationOptions<unknown, DefaultError, Options<AuthControllerResetPasswordData>> => {
    const mutationOptions: UseMutationOptions<unknown, DefaultError, Options<AuthControllerResetPasswordData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await authControllerResetPassword({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const authControllerRefreshMutation = (options?: Partial<Options<AuthControllerRefreshData>>): UseMutationOptions<unknown, DefaultError, Options<AuthControllerRefreshData>> => {
    const mutationOptions: UseMutationOptions<unknown, DefaultError, Options<AuthControllerRefreshData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await authControllerRefresh({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const authControllerLogoutMutation = (options?: Partial<Options<AuthControllerLogoutData>>): UseMutationOptions<unknown, DefaultError, Options<AuthControllerLogoutData>> => {
    const mutationOptions: UseMutationOptions<unknown, DefaultError, Options<AuthControllerLogoutData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await authControllerLogout({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const userControllerFindAllQueryKey = (options?: Options<UserControllerFindAllData>) => createQueryKey('userControllerFindAll', options);

export const userControllerFindAllOptions = (options?: Options<UserControllerFindAllData>) => queryOptions<unknown, DefaultError, unknown, ReturnType<typeof userControllerFindAllQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await userControllerFindAll({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: userControllerFindAllQueryKey(options)
});

export const userControllerCreateMutation = (options?: Partial<Options<UserControllerCreateData>>): UseMutationOptions<unknown, DefaultError, Options<UserControllerCreateData>> => {
    const mutationOptions: UseMutationOptions<unknown, DefaultError, Options<UserControllerCreateData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await userControllerCreate({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const userControllerRemoveMutation = (options?: Partial<Options<UserControllerRemoveData>>): UseMutationOptions<unknown, DefaultError, Options<UserControllerRemoveData>> => {
    const mutationOptions: UseMutationOptions<unknown, DefaultError, Options<UserControllerRemoveData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await userControllerRemove({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const userControllerFindOneQueryKey = (options: Options<UserControllerFindOneData>) => createQueryKey('userControllerFindOne', options);

export const userControllerFindOneOptions = (options: Options<UserControllerFindOneData>) => queryOptions<unknown, DefaultError, unknown, ReturnType<typeof userControllerFindOneQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await userControllerFindOne({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: userControllerFindOneQueryKey(options)
});

export const userControllerUpdateMutation = (options?: Partial<Options<UserControllerUpdateData>>): UseMutationOptions<unknown, DefaultError, Options<UserControllerUpdateData>> => {
    const mutationOptions: UseMutationOptions<unknown, DefaultError, Options<UserControllerUpdateData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await userControllerUpdate({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const lessonControllerFindAllQueryKey = (options?: Options<LessonControllerFindAllData>) => createQueryKey('lessonControllerFindAll', options);

export const lessonControllerFindAllOptions = (options?: Options<LessonControllerFindAllData>) => queryOptions<unknown, DefaultError, unknown, ReturnType<typeof lessonControllerFindAllQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await lessonControllerFindAll({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: lessonControllerFindAllQueryKey(options)
});

export const lessonControllerCreateMutation = (options?: Partial<Options<LessonControllerCreateData>>): UseMutationOptions<unknown, DefaultError, Options<LessonControllerCreateData>> => {
    const mutationOptions: UseMutationOptions<unknown, DefaultError, Options<LessonControllerCreateData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await lessonControllerCreate({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const lessonControllerRemoveMutation = (options?: Partial<Options<LessonControllerRemoveData>>): UseMutationOptions<unknown, DefaultError, Options<LessonControllerRemoveData>> => {
    const mutationOptions: UseMutationOptions<unknown, DefaultError, Options<LessonControllerRemoveData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await lessonControllerRemove({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const lessonControllerFindOneQueryKey = (options: Options<LessonControllerFindOneData>) => createQueryKey('lessonControllerFindOne', options);

export const lessonControllerFindOneOptions = (options: Options<LessonControllerFindOneData>) => queryOptions<unknown, DefaultError, unknown, ReturnType<typeof lessonControllerFindOneQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await lessonControllerFindOne({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: lessonControllerFindOneQueryKey(options)
});

export const lessonControllerUpdateMutation = (options?: Partial<Options<LessonControllerUpdateData>>): UseMutationOptions<unknown, DefaultError, Options<LessonControllerUpdateData>> => {
    const mutationOptions: UseMutationOptions<unknown, DefaultError, Options<LessonControllerUpdateData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await lessonControllerUpdate({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};
