// This file is auto-generated by @hey-api/openapi-ts

import { type DefaultError, queryOptions, type UseMutationOptions } from '@tanstack/react-query';

import { client } from '../client.gen';
import { appControllerGetHello, authControllerForgotPassword, authControllerLogin, authControllerLogout, authControllerRefresh, authControllerRegister, authControllerResendVerification, authControllerResetPassword, authControllerVerifyEmail, lessonControllerGetLessonById, lessonControllerGetRecommended, lessonControllerSearch, lessonControllerStartLesson, lessonControllerUpdateProgress, type Options, speechControllerAnalyzeSpeech, speechControllerCompareSpeech, speechControllerCreate, speechControllerFindAll, speechControllerFindOne, speechControllerGenerateAudio, speechControllerGetPhonemes, speechControllerGetSupportedLanguages, speechControllerRemove, speechControllerUpdate, userControllerProfile, userControllerUpdateUserProfile } from '../sdk.gen';
import type { AppControllerGetHelloData, AuthControllerForgotPasswordData, AuthControllerLoginData, AuthControllerLogoutData, AuthControllerRefreshData, AuthControllerRegisterData, AuthControllerResendVerificationData, AuthControllerResetPasswordData, AuthControllerVerifyEmailData, LessonControllerGetLessonByIdData, LessonControllerGetRecommendedData, LessonControllerSearchData, LessonControllerStartLessonData, LessonControllerUpdateProgressData, SpeechControllerAnalyzeSpeechData, SpeechControllerCompareSpeechData, SpeechControllerCreateData, SpeechControllerFindAllData, SpeechControllerFindOneData, SpeechControllerGenerateAudioData, SpeechControllerGetPhonemesData, SpeechControllerGetSupportedLanguagesData, SpeechControllerRemoveData, SpeechControllerUpdateData, UserControllerProfileData, UserControllerUpdateUserProfileData } from '../types.gen';

export type QueryKey<TOptions extends Options> = [
    Pick<TOptions, 'baseUrl' | 'body' | 'headers' | 'path' | 'query'> & {
        _id: string;
        _infinite?: boolean;
        tags?: ReadonlyArray<string>;
    }
];

const createQueryKey = <TOptions extends Options>(id: string, options?: TOptions, infinite?: boolean, tags?: ReadonlyArray<string>): [
    QueryKey<TOptions>[0]
] => {
    const params: QueryKey<TOptions>[0] = { _id: id, baseUrl: options?.baseUrl || (options?.client ?? client).getConfig().baseUrl } as QueryKey<TOptions>[0];
    if (infinite) {
        params._infinite = infinite;
    }
    if (tags) {
        params.tags = tags;
    }
    if (options?.body) {
        params.body = options.body;
    }
    if (options?.headers) {
        params.headers = options.headers;
    }
    if (options?.path) {
        params.path = options.path;
    }
    if (options?.query) {
        params.query = options.query;
    }
    return [params];
};

export const appControllerGetHelloQueryKey = (options?: Options<AppControllerGetHelloData>) => createQueryKey('appControllerGetHello', options);

/**
 * Get hello message
 */
export const appControllerGetHelloOptions = (options?: Options<AppControllerGetHelloData>) => queryOptions<unknown, DefaultError, unknown, ReturnType<typeof appControllerGetHelloQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await appControllerGetHello({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: appControllerGetHelloQueryKey(options)
});

/**
 * Register a new user
 */
export const authControllerRegisterMutation = (options?: Partial<Options<AuthControllerRegisterData>>): UseMutationOptions<unknown, DefaultError, Options<AuthControllerRegisterData>> => {
    const mutationOptions: UseMutationOptions<unknown, DefaultError, Options<AuthControllerRegisterData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await authControllerRegister({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

/**
 * Login user
 */
export const authControllerLoginMutation = (options?: Partial<Options<AuthControllerLoginData>>): UseMutationOptions<unknown, DefaultError, Options<AuthControllerLoginData>> => {
    const mutationOptions: UseMutationOptions<unknown, DefaultError, Options<AuthControllerLoginData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await authControllerLogin({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

/**
 * Verify user email
 */
export const authControllerVerifyEmailMutation = (options?: Partial<Options<AuthControllerVerifyEmailData>>): UseMutationOptions<unknown, DefaultError, Options<AuthControllerVerifyEmailData>> => {
    const mutationOptions: UseMutationOptions<unknown, DefaultError, Options<AuthControllerVerifyEmailData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await authControllerVerifyEmail({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

/**
 * Resend verification
 */
export const authControllerResendVerificationMutation = (options?: Partial<Options<AuthControllerResendVerificationData>>): UseMutationOptions<unknown, DefaultError, Options<AuthControllerResendVerificationData>> => {
    const mutationOptions: UseMutationOptions<unknown, DefaultError, Options<AuthControllerResendVerificationData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await authControllerResendVerification({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

/**
 * Request password reset
 */
export const authControllerForgotPasswordMutation = (options?: Partial<Options<AuthControllerForgotPasswordData>>): UseMutationOptions<unknown, DefaultError, Options<AuthControllerForgotPasswordData>> => {
    const mutationOptions: UseMutationOptions<unknown, DefaultError, Options<AuthControllerForgotPasswordData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await authControllerForgotPassword({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

/**
 * Reset user password
 */
export const authControllerResetPasswordMutation = (options?: Partial<Options<AuthControllerResetPasswordData>>): UseMutationOptions<unknown, DefaultError, Options<AuthControllerResetPasswordData>> => {
    const mutationOptions: UseMutationOptions<unknown, DefaultError, Options<AuthControllerResetPasswordData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await authControllerResetPassword({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const authControllerRefreshMutation = (options?: Partial<Options<AuthControllerRefreshData>>): UseMutationOptions<unknown, DefaultError, Options<AuthControllerRefreshData>> => {
    const mutationOptions: UseMutationOptions<unknown, DefaultError, Options<AuthControllerRefreshData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await authControllerRefresh({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const authControllerLogoutMutation = (options?: Partial<Options<AuthControllerLogoutData>>): UseMutationOptions<unknown, DefaultError, Options<AuthControllerLogoutData>> => {
    const mutationOptions: UseMutationOptions<unknown, DefaultError, Options<AuthControllerLogoutData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await authControllerLogout({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const userControllerProfileQueryKey = (options?: Options<UserControllerProfileData>) => createQueryKey('userControllerProfile', options);

export const userControllerProfileOptions = (options?: Options<UserControllerProfileData>) => queryOptions<unknown, DefaultError, unknown, ReturnType<typeof userControllerProfileQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await userControllerProfile({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: userControllerProfileQueryKey(options)
});

export const userControllerUpdateUserProfileMutation = (options?: Partial<Options<UserControllerUpdateUserProfileData>>): UseMutationOptions<unknown, DefaultError, Options<UserControllerUpdateUserProfileData>> => {
    const mutationOptions: UseMutationOptions<unknown, DefaultError, Options<UserControllerUpdateUserProfileData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await userControllerUpdateUserProfile({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const lessonControllerGetRecommendedQueryKey = (options?: Options<LessonControllerGetRecommendedData>) => createQueryKey('lessonControllerGetRecommended', options);

export const lessonControllerGetRecommendedOptions = (options?: Options<LessonControllerGetRecommendedData>) => queryOptions<unknown, DefaultError, unknown, ReturnType<typeof lessonControllerGetRecommendedQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await lessonControllerGetRecommended({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: lessonControllerGetRecommendedQueryKey(options)
});

export const lessonControllerSearchQueryKey = (options?: Options<LessonControllerSearchData>) => createQueryKey('lessonControllerSearch', options);

export const lessonControllerSearchOptions = (options?: Options<LessonControllerSearchData>) => queryOptions<unknown, DefaultError, unknown, ReturnType<typeof lessonControllerSearchQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await lessonControllerSearch({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: lessonControllerSearchQueryKey(options)
});

export const lessonControllerGetLessonByIdQueryKey = (options: Options<LessonControllerGetLessonByIdData>) => createQueryKey('lessonControllerGetLessonById', options);

export const lessonControllerGetLessonByIdOptions = (options: Options<LessonControllerGetLessonByIdData>) => queryOptions<unknown, DefaultError, unknown, ReturnType<typeof lessonControllerGetLessonByIdQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await lessonControllerGetLessonById({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: lessonControllerGetLessonByIdQueryKey(options)
});

export const lessonControllerStartLessonMutation = (options?: Partial<Options<LessonControllerStartLessonData>>): UseMutationOptions<unknown, DefaultError, Options<LessonControllerStartLessonData>> => {
    const mutationOptions: UseMutationOptions<unknown, DefaultError, Options<LessonControllerStartLessonData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await lessonControllerStartLesson({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const lessonControllerUpdateProgressMutation = (options?: Partial<Options<LessonControllerUpdateProgressData>>): UseMutationOptions<unknown, DefaultError, Options<LessonControllerUpdateProgressData>> => {
    const mutationOptions: UseMutationOptions<unknown, DefaultError, Options<LessonControllerUpdateProgressData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await lessonControllerUpdateProgress({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const speechControllerGetSupportedLanguagesQueryKey = (options?: Options<SpeechControllerGetSupportedLanguagesData>) => createQueryKey('speechControllerGetSupportedLanguages', options);

export const speechControllerGetSupportedLanguagesOptions = (options?: Options<SpeechControllerGetSupportedLanguagesData>) => queryOptions<unknown, DefaultError, unknown, ReturnType<typeof speechControllerGetSupportedLanguagesQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await speechControllerGetSupportedLanguages({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: speechControllerGetSupportedLanguagesQueryKey(options)
});

export const speechControllerGetPhonemesQueryKey = (options: Options<SpeechControllerGetPhonemesData>) => createQueryKey('speechControllerGetPhonemes', options);

export const speechControllerGetPhonemesOptions = (options: Options<SpeechControllerGetPhonemesData>) => queryOptions<unknown, DefaultError, unknown, ReturnType<typeof speechControllerGetPhonemesQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await speechControllerGetPhonemes({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: speechControllerGetPhonemesQueryKey(options)
});

export const speechControllerAnalyzeSpeechMutation = (options?: Partial<Options<SpeechControllerAnalyzeSpeechData>>): UseMutationOptions<unknown, DefaultError, Options<SpeechControllerAnalyzeSpeechData>> => {
    const mutationOptions: UseMutationOptions<unknown, DefaultError, Options<SpeechControllerAnalyzeSpeechData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await speechControllerAnalyzeSpeech({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const speechControllerCompareSpeechMutation = (options?: Partial<Options<SpeechControllerCompareSpeechData>>): UseMutationOptions<unknown, DefaultError, Options<SpeechControllerCompareSpeechData>> => {
    const mutationOptions: UseMutationOptions<unknown, DefaultError, Options<SpeechControllerCompareSpeechData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await speechControllerCompareSpeech({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const speechControllerGenerateAudioMutation = (options?: Partial<Options<SpeechControllerGenerateAudioData>>): UseMutationOptions<unknown, DefaultError, Options<SpeechControllerGenerateAudioData>> => {
    const mutationOptions: UseMutationOptions<unknown, DefaultError, Options<SpeechControllerGenerateAudioData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await speechControllerGenerateAudio({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const speechControllerFindAllQueryKey = (options?: Options<SpeechControllerFindAllData>) => createQueryKey('speechControllerFindAll', options);

export const speechControllerFindAllOptions = (options?: Options<SpeechControllerFindAllData>) => queryOptions<unknown, DefaultError, unknown, ReturnType<typeof speechControllerFindAllQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await speechControllerFindAll({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: speechControllerFindAllQueryKey(options)
});

export const speechControllerCreateMutation = (options?: Partial<Options<SpeechControllerCreateData>>): UseMutationOptions<unknown, DefaultError, Options<SpeechControllerCreateData>> => {
    const mutationOptions: UseMutationOptions<unknown, DefaultError, Options<SpeechControllerCreateData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await speechControllerCreate({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const speechControllerRemoveMutation = (options?: Partial<Options<SpeechControllerRemoveData>>): UseMutationOptions<unknown, DefaultError, Options<SpeechControllerRemoveData>> => {
    const mutationOptions: UseMutationOptions<unknown, DefaultError, Options<SpeechControllerRemoveData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await speechControllerRemove({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const speechControllerFindOneQueryKey = (options: Options<SpeechControllerFindOneData>) => createQueryKey('speechControllerFindOne', options);

export const speechControllerFindOneOptions = (options: Options<SpeechControllerFindOneData>) => queryOptions<unknown, DefaultError, unknown, ReturnType<typeof speechControllerFindOneQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await speechControllerFindOne({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: speechControllerFindOneQueryKey(options)
});

export const speechControllerUpdateMutation = (options?: Partial<Options<SpeechControllerUpdateData>>): UseMutationOptions<unknown, DefaultError, Options<SpeechControllerUpdateData>> => {
    const mutationOptions: UseMutationOptions<unknown, DefaultError, Options<SpeechControllerUpdateData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await speechControllerUpdate({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};
