version: '3.8'

services:
  app:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    image: speak-ai:latest
    ports:
      - "5000:5000"
    env_file:
      - ../.env
    depends_on:
      - postgres
      - migrate
    extra_hosts:
      - "host.docker.internal:host-gateway"

  migrate:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    env_file:
      - ../.env
    depends_on:
      - postgres
    command: >
      sh -c "npx prisma migrate deploy"

  postgres:
    image: postgres:15
    container_name: ${DATABASE_HOST}
    restart: always
    environment:
      - POSTGRES_USER=${DATABASE_USERNAME}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRES_DB=${DATABASE_NAME}
    ports:
      - '5433:${DATABASE_PORT}'
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: