// This file is auto-generated by @hey-api/openapi-ts

import type { Client, Options as Options2, TDataShape } from './client';
import { client } from './client.gen';
import type { AppControllerGetHelloData, AppControllerGetHelloResponses, AuthControllerForgotPasswordData, AuthControllerForgotPasswordResponses, AuthControllerLoginData, AuthControllerLoginErrors, AuthControllerLoginResponses, AuthControllerLogoutData, AuthControllerLogoutResponses, AuthControllerRefreshData, AuthControllerRefreshResponses, AuthControllerRegisterData, AuthControllerRegisterErrors, AuthControllerRegisterResponses, AuthControllerResendVerificationData, AuthControllerResendVerificationResponses, AuthControllerResetPasswordData, AuthControllerResetPasswordErrors, AuthControllerResetPasswordResponses, AuthControllerVerifyEmailData, AuthControllerVerifyEmailErrors, AuthControllerVerifyEmailResponses, LessonControllerGetLessonByIdData, LessonControllerGetLessonByIdResponses, LessonControllerGetRecommendedData, LessonControllerGetRecommendedResponses, LessonControllerSearchData, LessonControllerSearchResponses, LessonControllerStartLessonData, LessonControllerStartLessonResponses, LessonControllerUpdateProgressData, LessonControllerUpdateProgressResponses, SpeechControllerAnalyzeSpeechData, SpeechControllerAnalyzeSpeechResponses, SpeechControllerCompareSpeechData, SpeechControllerCompareSpeechResponses, SpeechControllerCreateData, SpeechControllerCreateResponses, SpeechControllerFindAllData, SpeechControllerFindAllResponses, SpeechControllerFindOneData, SpeechControllerFindOneResponses, SpeechControllerGenerateAudioData, SpeechControllerGenerateAudioResponses, SpeechControllerGetPhonemesData, SpeechControllerGetPhonemesResponses, SpeechControllerGetSupportedLanguagesData, SpeechControllerGetSupportedLanguagesResponses, SpeechControllerRemoveData, SpeechControllerRemoveResponses, SpeechControllerUpdateData, SpeechControllerUpdateResponses, UserControllerProfileData, UserControllerProfileResponses, UserControllerUpdateUserProfileData, UserControllerUpdateUserProfileResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> = Options2<TData, ThrowOnError> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

/**
 * Get hello message
 */
export const appControllerGetHello = <ThrowOnError extends boolean = false>(options?: Options<AppControllerGetHelloData, ThrowOnError>) => (options?.client ?? client).get<AppControllerGetHelloResponses, unknown, ThrowOnError>({ url: '/', ...options });

/**
 * Register a new user
 */
export const authControllerRegister = <ThrowOnError extends boolean = false>(options: Options<AuthControllerRegisterData, ThrowOnError>) => (options.client ?? client).post<AuthControllerRegisterResponses, AuthControllerRegisterErrors, ThrowOnError>({
    url: '/auth/register',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Login user
 */
export const authControllerLogin = <ThrowOnError extends boolean = false>(options: Options<AuthControllerLoginData, ThrowOnError>) => (options.client ?? client).post<AuthControllerLoginResponses, AuthControllerLoginErrors, ThrowOnError>({
    url: '/auth/login',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Verify user email
 */
export const authControllerVerifyEmail = <ThrowOnError extends boolean = false>(options: Options<AuthControllerVerifyEmailData, ThrowOnError>) => (options.client ?? client).post<AuthControllerVerifyEmailResponses, AuthControllerVerifyEmailErrors, ThrowOnError>({
    url: '/auth/verify-email',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Resend verification
 */
export const authControllerResendVerification = <ThrowOnError extends boolean = false>(options: Options<AuthControllerResendVerificationData, ThrowOnError>) => (options.client ?? client).post<AuthControllerResendVerificationResponses, unknown, ThrowOnError>({
    url: '/auth/resend-verification',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Request password reset
 */
export const authControllerForgotPassword = <ThrowOnError extends boolean = false>(options: Options<AuthControllerForgotPasswordData, ThrowOnError>) => (options.client ?? client).post<AuthControllerForgotPasswordResponses, unknown, ThrowOnError>({
    url: '/auth/forgot-password',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Reset user password
 */
export const authControllerResetPassword = <ThrowOnError extends boolean = false>(options: Options<AuthControllerResetPasswordData, ThrowOnError>) => (options.client ?? client).post<AuthControllerResetPasswordResponses, AuthControllerResetPasswordErrors, ThrowOnError>({
    url: '/auth/reset-password',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

export const authControllerRefresh = <ThrowOnError extends boolean = false>(options?: Options<AuthControllerRefreshData, ThrowOnError>) => (options?.client ?? client).post<AuthControllerRefreshResponses, unknown, ThrowOnError>({ url: '/auth/refresh', ...options });

export const authControllerLogout = <ThrowOnError extends boolean = false>(options?: Options<AuthControllerLogoutData, ThrowOnError>) => (options?.client ?? client).post<AuthControllerLogoutResponses, unknown, ThrowOnError>({ url: '/auth/logout', ...options });

export const userControllerProfile = <ThrowOnError extends boolean = false>(options?: Options<UserControllerProfileData, ThrowOnError>) => (options?.client ?? client).get<UserControllerProfileResponses, unknown, ThrowOnError>({ url: '/user/profile', ...options });

export const userControllerUpdateUserProfile = <ThrowOnError extends boolean = false>(options: Options<UserControllerUpdateUserProfileData, ThrowOnError>) => (options.client ?? client).put<UserControllerUpdateUserProfileResponses, unknown, ThrowOnError>({
    url: '/user/{userId}',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

export const lessonControllerGetRecommended = <ThrowOnError extends boolean = false>(options?: Options<LessonControllerGetRecommendedData, ThrowOnError>) => (options?.client ?? client).get<LessonControllerGetRecommendedResponses, unknown, ThrowOnError>({ url: '/lesson/recommend', ...options });

export const lessonControllerSearch = <ThrowOnError extends boolean = false>(options?: Options<LessonControllerSearchData, ThrowOnError>) => (options?.client ?? client).get<LessonControllerSearchResponses, unknown, ThrowOnError>({ url: '/lesson/search', ...options });

export const lessonControllerGetLessonById = <ThrowOnError extends boolean = false>(options: Options<LessonControllerGetLessonByIdData, ThrowOnError>) => (options.client ?? client).get<LessonControllerGetLessonByIdResponses, unknown, ThrowOnError>({ url: '/lesson/{id}', ...options });

export const lessonControllerStartLesson = <ThrowOnError extends boolean = false>(options: Options<LessonControllerStartLessonData, ThrowOnError>) => (options.client ?? client).post<LessonControllerStartLessonResponses, unknown, ThrowOnError>({ url: '/lesson/{id}/start', ...options });

export const lessonControllerUpdateProgress = <ThrowOnError extends boolean = false>(options: Options<LessonControllerUpdateProgressData, ThrowOnError>) => (options.client ?? client).put<LessonControllerUpdateProgressResponses, unknown, ThrowOnError>({
    url: '/lesson/id/progress',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

export const speechControllerGetSupportedLanguages = <ThrowOnError extends boolean = false>(options?: Options<SpeechControllerGetSupportedLanguagesData, ThrowOnError>) => (options?.client ?? client).get<SpeechControllerGetSupportedLanguagesResponses, unknown, ThrowOnError>({ url: '/speech/supported-languages', ...options });

export const speechControllerGetPhonemes = <ThrowOnError extends boolean = false>(options: Options<SpeechControllerGetPhonemesData, ThrowOnError>) => (options.client ?? client).get<SpeechControllerGetPhonemesResponses, unknown, ThrowOnError>({ url: '/speech/phonemes/{language}', ...options });

export const speechControllerAnalyzeSpeech = <ThrowOnError extends boolean = false>(options: Options<SpeechControllerAnalyzeSpeechData, ThrowOnError>) => (options.client ?? client).post<SpeechControllerAnalyzeSpeechResponses, unknown, ThrowOnError>({
    url: '/speech/analyze',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

export const speechControllerCompareSpeech = <ThrowOnError extends boolean = false>(options: Options<SpeechControllerCompareSpeechData, ThrowOnError>) => (options.client ?? client).post<SpeechControllerCompareSpeechResponses, unknown, ThrowOnError>({
    url: '/speech/compare',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

export const speechControllerGenerateAudio = <ThrowOnError extends boolean = false>(options: Options<SpeechControllerGenerateAudioData, ThrowOnError>) => (options.client ?? client).post<SpeechControllerGenerateAudioResponses, unknown, ThrowOnError>({
    url: '/speech/generate-audio',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

export const speechControllerFindAll = <ThrowOnError extends boolean = false>(options?: Options<SpeechControllerFindAllData, ThrowOnError>) => (options?.client ?? client).get<SpeechControllerFindAllResponses, unknown, ThrowOnError>({ url: '/speech', ...options });

export const speechControllerCreate = <ThrowOnError extends boolean = false>(options: Options<SpeechControllerCreateData, ThrowOnError>) => (options.client ?? client).post<SpeechControllerCreateResponses, unknown, ThrowOnError>({
    url: '/speech',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

export const speechControllerRemove = <ThrowOnError extends boolean = false>(options: Options<SpeechControllerRemoveData, ThrowOnError>) => (options.client ?? client).delete<SpeechControllerRemoveResponses, unknown, ThrowOnError>({ url: '/speech/{id}', ...options });

export const speechControllerFindOne = <ThrowOnError extends boolean = false>(options: Options<SpeechControllerFindOneData, ThrowOnError>) => (options.client ?? client).get<SpeechControllerFindOneResponses, unknown, ThrowOnError>({ url: '/speech/{id}', ...options });

export const speechControllerUpdate = <ThrowOnError extends boolean = false>(options: Options<SpeechControllerUpdateData, ThrowOnError>) => (options.client ?? client).patch<SpeechControllerUpdateResponses, unknown, ThrowOnError>({
    url: '/speech/{id}',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});
