// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: string;
};

export type RegisterDto = {
    /**
     * User email address
     */
    email: string;
    /**
     * Password with uppercase, lowercase, number and special character
     */
    password: string;
    /**
     * User first name
     */
    firstName: string;
    /**
     * User last name
     */
    lastName: string;
    /**
     * User native language
     */
    nativeLanguage: string;
    /**
     * Language user wants to learn
     */
    learningLanguage: string;
};

export type LoginDto = {
    /**
     * User email address
     */
    email: string;
    /**
     * User password
     */
    password: string;
};

export type VerifyEmailDto = {
    /**
     * Email verification token
     */
    token: string;
};

export type ResendVerificationDto = {
    [key: string]: unknown;
};

export type ForgotPasswordDto = {
    /**
     * Email address to send reset link
     */
    email: string;
};

export type ResetPasswordDto = {
    /**
     * Password reset token
     */
    token: string;
    /**
     * New password with uppercase, lowercase, number and special character
     */
    newPassword: string;
};

export type UpdateUserDto = {
    [key: string]: unknown;
};

export type UpdateLessonDto = {
    [key: string]: unknown;
};

export type AnalyzeSpeechDto = {
    [key: string]: unknown;
};

export type CompareSpeechDto = {
    [key: string]: unknown;
};

export type GenerateAudioDto = {
    [key: string]: unknown;
};

export type CreateSpeechDto = {
    [key: string]: unknown;
};

export type UpdateSpeechDto = {
    [key: string]: unknown;
};

export type AppControllerGetHelloData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/';
};

export type AppControllerGetHelloResponses = {
    /**
     * Returns hello message
     */
    200: unknown;
};

export type AuthControllerRegisterData = {
    body: RegisterDto;
    path?: never;
    query?: never;
    url: '/auth/register';
};

export type AuthControllerRegisterErrors = {
    /**
     * Email already exists
     */
    409: unknown;
};

export type AuthControllerRegisterResponses = {
    /**
     * User registered successfully
     */
    201: unknown;
};

export type AuthControllerLoginData = {
    body: LoginDto;
    path?: never;
    query?: never;
    url: '/auth/login';
};

export type AuthControllerLoginErrors = {
    /**
     * Invalid credentials
     */
    401: unknown;
};

export type AuthControllerLoginResponses = {
    /**
     * Login successful
     */
    200: unknown;
};

export type AuthControllerVerifyEmailData = {
    body: VerifyEmailDto;
    path?: never;
    query?: never;
    url: '/auth/verify-email';
};

export type AuthControllerVerifyEmailErrors = {
    /**
     * Invalid token
     */
    400: unknown;
};

export type AuthControllerVerifyEmailResponses = {
    /**
     * Email verified successfully
     */
    200: unknown;
};

export type AuthControllerResendVerificationData = {
    body: ResendVerificationDto;
    path?: never;
    query?: never;
    url: '/auth/resend-verification';
};

export type AuthControllerResendVerificationResponses = {
    201: unknown;
};

export type AuthControllerForgotPasswordData = {
    body: ForgotPasswordDto;
    path?: never;
    query?: never;
    url: '/auth/forgot-password';
};

export type AuthControllerForgotPasswordResponses = {
    /**
     * Reset link sent if account exists
     */
    200: unknown;
};

export type AuthControllerResetPasswordData = {
    body: ResetPasswordDto;
    path?: never;
    query?: never;
    url: '/auth/reset-password';
};

export type AuthControllerResetPasswordErrors = {
    /**
     * Invalid or expired token
     */
    400: unknown;
};

export type AuthControllerResetPasswordResponses = {
    /**
     * Password reset successfully
     */
    200: unknown;
};

export type AuthControllerRefreshData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/auth/refresh';
};

export type AuthControllerRefreshResponses = {
    201: unknown;
};

export type AuthControllerLogoutData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/auth/logout';
};

export type AuthControllerLogoutResponses = {
    201: unknown;
};

export type UserControllerProfileData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/user/profile';
};

export type UserControllerProfileResponses = {
    200: unknown;
};

export type UserControllerUpdateUserProfileData = {
    body: UpdateUserDto;
    path: {
        userId: string;
    };
    query?: never;
    url: '/user/{userId}';
};

export type UserControllerUpdateUserProfileResponses = {
    200: unknown;
};

export type LessonControllerGetRecommendedData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/lesson/recommend';
};

export type LessonControllerGetRecommendedResponses = {
    200: unknown;
};

export type LessonControllerSearchData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/lesson/search';
};

export type LessonControllerSearchResponses = {
    200: unknown;
};

export type LessonControllerGetLessonByIdData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/lesson/{id}';
};

export type LessonControllerGetLessonByIdResponses = {
    200: unknown;
};

export type LessonControllerStartLessonData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/lesson/{id}/start';
};

export type LessonControllerStartLessonResponses = {
    201: unknown;
};

export type LessonControllerUpdateProgressData = {
    body: UpdateLessonDto;
    path: {
        id: string;
    };
    query?: never;
    url: '/lesson/id/progress';
};

export type LessonControllerUpdateProgressResponses = {
    200: unknown;
};

export type DashboardControllerGetDashboardDataData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/dashboard';
};

export type DashboardControllerGetDashboardDataResponses = {
    200: unknown;
};

export type SpeechControllerGetSupportedLanguagesData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/speech/supported-languages';
};

export type SpeechControllerGetSupportedLanguagesResponses = {
    200: unknown;
};

export type SpeechControllerGetPhonemesData = {
    body?: never;
    path: {
        language: string;
    };
    query?: never;
    url: '/speech/phonemes/{language}';
};

export type SpeechControllerGetPhonemesResponses = {
    200: unknown;
};

export type SpeechControllerAnalyzeSpeechData = {
    body: AnalyzeSpeechDto;
    path?: never;
    query?: never;
    url: '/speech/analyze';
};

export type SpeechControllerAnalyzeSpeechResponses = {
    201: unknown;
};

export type SpeechControllerCompareSpeechData = {
    body: CompareSpeechDto;
    path?: never;
    query?: never;
    url: '/speech/compare';
};

export type SpeechControllerCompareSpeechResponses = {
    201: unknown;
};

export type SpeechControllerGenerateAudioData = {
    body: GenerateAudioDto;
    path?: never;
    query?: never;
    url: '/speech/generate-audio';
};

export type SpeechControllerGenerateAudioResponses = {
    201: unknown;
};

export type SpeechControllerFindAllData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/speech';
};

export type SpeechControllerFindAllResponses = {
    200: unknown;
};

export type SpeechControllerCreateData = {
    body: CreateSpeechDto;
    path?: never;
    query?: never;
    url: '/speech';
};

export type SpeechControllerCreateResponses = {
    201: unknown;
};

export type SpeechControllerRemoveData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/speech/{id}';
};

export type SpeechControllerRemoveResponses = {
    200: unknown;
};

export type SpeechControllerFindOneData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/speech/{id}';
};

export type SpeechControllerFindOneResponses = {
    200: unknown;
};

export type SpeechControllerUpdateData = {
    body: UpdateSpeechDto;
    path: {
        id: string;
    };
    query?: never;
    url: '/speech/{id}';
};

export type SpeechControllerUpdateResponses = {
    200: unknown;
};
